services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: virtualwallet_db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=WalletSecurePass123! 
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql 

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: virtualwallet_api
    ports:
      - "8080:8080" 
    depends_on:
      - db 
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=VirtualWalletDb;User=sa;Password=WalletSecurePass123!;TrustServerCertificate=True;

volumes:
  sqlserver_data: